name: CI/CD for WebLife-Diabetes

on:
  push:
    branches: [main]
    paths:
      - 'WebLife-Diabetes/**'
  pull_request:
    branches: [main]
    paths:
      - 'WebLife-Diabetes/**'

jobs:
  ci:
    name: Run Pre-commit + Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 在 WebLife-Diabetes 目录下运行 pre-commit 及依赖安装
      - name: Install Pre-commit
        run: |
          pip install pre-commit
          pre-commit install
        working-directory: WebLife-Diabetes

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files
        working-directory: WebLife-Diabetes

      - name: Install Node Dependencies
        run: npm install
        working-directory: WebLife-Diabetes

      - name: Run Node Tests
        run: npm test || echo "No JS tests found"
        working-directory: WebLife-Diabetes

      # 可选：如果有 Python 相关测试
      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: WebLife-Diabetes

      - name: Run Python Tests
        run: |
          if [ -d tests ]; then pytest; else echo "No Python tests found"; fi
        working-directory: WebLife-Diabetes

      # 打包时进入 WebLife-Diabetes 目录，打包内容的根目录即为项目文件
      - name: Zip artifact for deployment
        run: |
          cd WebLife-Diabetes
          zip -r ../release.zip . -x "**/node_modules/*" "**/.git/*" "**/.env" "**/*.class" "**/bin/*" "**/*.java"
          cd ..

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip

  cd:
    name: Deploy to Azure Web App
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WEBLIFE-DIABETES          # 请确保此处与 Azure Web App 名一致
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

      - name: Cleanup ZIP (Optional)
        run: rm -f release.zip
