version: '3.8'

services:
  catalogdb:
    image: postgres:15
    container_name: catalog_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CatalogDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - catalog_data:/var/lib/postgresql/data

volumes:
  catalog_data: