name: Build and deploy Node.js app to Azure Web App - WEBLIFE-DIABETES

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use Node.js 18.x to match your app requirements

      # Install dependencies and build the app (if needed)
      - name: Install Node Dependencies
        run: |
          npm ci --verbose
        working-directory: WebLife-Diabetes

      # Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          cd WebLife-Diabetes
          zip -r ../release.zip . -x "**/node_modules/*" "**/.git/*" "**/.env" "**/*.class" "**/bin/*" "**/*.java"
          cd ..
        
      # Upload the artifact for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs only after the build job is successful
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure using your credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WEBLIFE-DIABETES'  # Make sure this matches your Azure Web App name
          slot-name: 'Production'
          package: .

      # Optional cleanup: Remove the zip file after deployment
      - name: Cleanup ZIP (Optional)
        run: rm -f release.zip
