name: Build and Deploy WebLife-Diabetes to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FullStack_Projects/WebLife-Diabetes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run JS Tests
        run: npm test || echo "No JS tests found"

      - name: Zip for deployment
        run: |
          cd ..
          zip -r release.zip WebLife-Diabetes -x "**/node_modules/*" "**/.git/*" "**/*.class" "**/bin/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: FullStack_Projects/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: Unzip and check content
        run: unzip release.zip && ls -la WebLife-Diabetes

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WEBLIFE-DIABETES
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: WebLife-Diabetes
